### ISSUE TITLE
Batterieladestand wird mit dem Wert der (Ent-)Ladeleistung angegeben

### ISSUE THREAD

**Issue by FRMB6** [unl0ck/viessmann-gridbox-connector#3]
![image](https://github.com/unl0ck/viessmann-gridbox-connector/assets/163857685/dc9b2a95-db76-401a-a543-64298d840392)
Batterieladezustand schwankt zwicshen -400% und +400%, scheint also der Wert der (Ent-)ladeleistung zu sein.

Die Ladeleistung darf aber gerne als Extra Wert mit ausgegeben werden!

**Comment by unl0ck** [comment]
ja ich hab den falschen wert genommen, und initial falsch gecastet, wer lesen kann ist klar im vorteil.
ich bau das mit der power mal ein.
